# Generated by Django 5.1.2 on 2025-04-10 15:37

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='categories/', validators=[config.utils.image_validators.validate_image_size, config.utils.image_validators.validate_image_resolution]),
        ),
    ]
